name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Run build
        run: |
          npm run build
          cd dist
          zip ../dist.zip -r *.[^.]*
          echo "Build Successful"
      - name: Copy Terraform Folder
        run: |
          mkdir -p artifacts/terraform
          cp -r terraform artifacts/terraform
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist.zip
            artifacts/

  terraform-validate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4
      - name: Terraform Format
        run: |
          cd terraform
          terraform fmt -diff
          terraform fmt -write=true
      - name: Terraform Validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate