name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Run build
        run: npm run build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distfiles
          path: dist
          retention-days: 14

  prettier-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Run prettier
        run: npm run prettier:check

  csc-deploy:
    runs-on: ubuntu-latest
    needs: prettier-check
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: distfiles
          path: distfiles
      - name: Deploy client to prod
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: pro
          key: ${{ secrets.CLOUD_KEY }}
          port: 22
          source: distfiles/*
          rm: true
          target: htdocs/pro.code.sydney/
          strip_components: 1
